### PR TITLE
(documentation) Corrected Badges

### PR DESCRIPTION
**Pull request by gep13**
- They were still pointing at WormieCorp

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
@gep13 if you look at the develop branch, they are already updated, I usually never update the master branch until a new release is ready.

**Comment by AdmiringWorm** [comment]
https://github.com/cake-contrib/Cake.Transifex/blob/develop/README.md

with that said though, I noticed I have forgotten to update the myget packages url.

**Comment by AdmiringWorm** [comment]
as you can see from the front page of the repo now, the Readme had already been updated.
As such I'm closing this PR.

**Comment by gep13** [comment]
@AdmiringWorm ah, my bad! I had forgotten about that.

**Pull request closed without merging**
